package com.AnormaisEBruna.petshop.gui.views;

import com.AnormaisEBruna.petshop.gui.components.pages.InitialPage;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class Cuidador  extends  JPanel{
    NovoCuidador cadastropage = new NovoCuidador();
    EditarCuidador editpage = new EditarCuidador();

    Object nome,email,novonome,novoemail;


    /**
     * Creates new form Usuarios
     */

    public void setconfpanel(JPanel p){
        p.setSize(1024,1024);
        p.setLocation(0,0 ); // setlocation 0 p ser no meio da tela
        cuidadorPanel.add(p);
        cuidadorPanel.revalidate();
        cuidadorPanel.repaint();
    }
    public Cuidador() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        cuidadorPanel = new JPanel();
        titlePage = new javax.swing.JLabel();
        novoCuidadorButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        tableCuidadores = new javax.swing.JTable();


        setPreferredSize(new java.awt.Dimension(1024, 1024));
        setLayout(new FlowLayout());

        cuidadorPanel.setBackground(new java.awt.Color(255, 255, 255));
        cuidadorPanel.setPreferredSize(new java.awt.Dimension(1024, 1024));

        titlePage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titlePage.setText("Cuidadores");

        novoCuidadorButton.setText("Novo Cuidador");
        novoCuidadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCuidadorButtonActionPerformed(evt);
            }
        });

        editarButton.setText("Editar");
        editarButton.setMaximumSize(new java.awt.Dimension(75, 22));
        editarButton.setMinimumSize(new java.awt.Dimension(75, 22));
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.setMaximumSize(new java.awt.Dimension(75, 22));
        excluirButton.setMinimumSize(new java.awt.Dimension(75, 22));
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        tableCuidadores.setModel(new DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Nome", "E-mail"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCuidadores.setToolTipText("");
        tableCuidadores.setShowGrid(false);
        scrollPanel.setViewportView(tableCuidadores);

        javax.swing.GroupLayout cuidadorPanelLayout = new javax.swing.GroupLayout(cuidadorPanel);
        cuidadorPanel.setLayout(cuidadorPanelLayout);
        cuidadorPanelLayout.setHorizontalGroup(
                cuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cuidadorPanelLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(cuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(cuidadorPanelLayout.createSequentialGroup()
                                                .addComponent(titlePage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                                        .addGroup(cuidadorPanelLayout.createSequentialGroup()
                                                .addComponent(novoCuidadorButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(125, 125, 125))
        );
        cuidadorPanelLayout.setVerticalGroup(
                cuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cuidadorPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(titlePage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(cuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(novoCuidadorButton)
                                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(371, Short.MAX_VALUE))
        );
        cuidadorPanel.setBounds(0,0,-1,-1);
        add(cuidadorPanel);
    }// </editor-fold>
    private void novoCuidadorButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        cuidadorPanel.removeAll();
        setconfpanel(cadastropage);

    }
    // atualiza os dados antes de voltar para essa pagina.
    public void refreshtable(){
        DefaultTableModel tablecuidadores = (DefaultTableModel) tableCuidadores.getModel();
        Object[] dados = {nome,email,"indisponivel"};
        tablecuidadores.addRow(dados);
    }
    public void setNome(Object nome){
        this.nome=nome;
    }
    public void setEmail(Object email){
        this.email=email;
    }
    public void editTable(){
        DefaultTableModel tabelaUsuario = (DefaultTableModel) tableCuidadores.getModel();
        tabelaUsuario.setValueAt(novonome, tableCuidadores.getSelectedRow(), 0);
        tabelaUsuario.setValueAt(novoemail, tableCuidadores.getSelectedRow(), 1);
        tabelaUsuario.setValueAt("agr",tableCuidadores.getSelectedRow(),2);
    }
    public void setNovoNome(Object novonome){
        this.novonome=novonome;
    }
    public void setNovoEmail(Object novoemail){
        this.novoemail=novoemail;
    }

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(tableCuidadores.getSelectedRow() != -1){
            cuidadorPanel.removeAll();
            setconfpanel(editpage);
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um cuidador para Editar");
        }
    }

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(tableCuidadores.getSelectedRow() != -1){
            DefaultTableModel tabelaUsuario = (DefaultTableModel) tableCuidadores.getModel();
            tabelaUsuario.removeRow(tableCuidadores.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um cuidador para Excluir");
        }
    }
    public JPanel cuidadorPanel;
    private JButton editarButton;
    private JButton excluirButton;
    private JButton novoCuidadorButton;
    private JTable tableCuidadores;
    private JScrollPane scrollPanel;
    private JLabel titlePage;
   
}
