package com.AnormaisEBruna.petshop.gui.views;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import com.AnormaisEBruna.petshop.contracts.gui.GUIManager;

import javax.swing.*;

/**
 *
 * @author detup
 */
public class EditarUsuario extends JPanel {

    /**
     * Creates new form EditarUsuario
     */
    public void setconfpanel(JPanel p){
        p.setSize(1024,1024);
        p.setLocation(0,0 ); // setlocation 0 p ser no meio da tela
        EditarUsuarioPanel.add(p);
        EditarUsuarioPanel.revalidate();
        EditarUsuarioPanel.repaint();
    }
    public EditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        EditarUsuarioPanel = new JPanel();
        novoNomeUsuario = new JFormattedTextField();
        novoEmailUsuario = new JFormattedTextField();
        jLabel3 = new JLabel();
        editarUsuarioButton = new JButton();
        jLabel5 = new JLabel();
        jLabel1 = new JLabel();

        setPreferredSize(new java.awt.Dimension(1024, 1024));

        EditarUsuarioPanel.setBackground(new java.awt.Color(255, 255, 255));
        EditarUsuarioPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        EditarUsuarioPanel.setPreferredSize(new java.awt.Dimension(1024, 1024));

        novoNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoNomeUsuarioActionPerformed(evt);
            }
        });

        novoEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEmailUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Novo Nome");

        editarUsuarioButton.setBackground(new java.awt.Color(0, 102, 204));
        editarUsuarioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editarUsuarioButton.setForeground(new java.awt.Color(255, 255, 255));
        editarUsuarioButton.setText("Editar");
        editarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Novo E-mail");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Editar Usuário");

        GroupLayout EditarUsuarioPanelLayout = new GroupLayout(EditarUsuarioPanel);
        EditarUsuarioPanel.setLayout(EditarUsuarioPanelLayout);
        EditarUsuarioPanelLayout.setHorizontalGroup(
            EditarUsuarioPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, EditarUsuarioPanelLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoNomeUsuario)
                    .addComponent(novoEmailUsuario, GroupLayout.PREFERRED_SIZE, 318, GroupLayout.PREFERRED_SIZE))
                .addGap(350, 350, 350))
            .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(editarUsuarioButton, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditarUsuarioPanelLayout.setVerticalGroup(
            EditarUsuarioPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoNomeUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoEmailUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(editarUsuarioButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(EditarUsuarioPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EditarUsuarioPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void novoEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void novoNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void editarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        if(novoEmailUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nome Invalido!");
        }else if(novoNomeUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Email Invalido!");
        }else{
            Usuarios layoutusuario = new Usuarios();
            JOptionPane.showMessageDialog(null,"Editado com Sucesso!");
//            layoutusuario.setNovoEmail(novoEmailUsuario.getText());
//            layoutusuario.setNovoNome(novoNomeUsuario.getText());
//            layoutusuario.editTable();
            EditarUsuarioPanel.removeAll();
            setconfpanel(layoutusuario);   
        }
    }                                                   


    // Variables declaration - do not modify                     
    private JPanel EditarUsuarioPanel;
    public JButton editarUsuarioButton;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel5;
    public JFormattedTextField novoEmailUsuario;
    public JFormattedTextField novoNomeUsuario;
    // End of variables declaration                   
}
