package com.AnormaisEBruna.petshop.gui.views;


import javax.swing.*;

/**
 *
 * @author bielf
 */
public class EditarCuidador extends JPanel {

    public void setconfpanel(JPanel p){
        p.setSize(1024,1024);
        p.setLocation(0,0 ); // setlocation 0 p ser no meio da tela
        editarCuidadorPanel.add(p);
        editarCuidadorPanel.revalidate();
        editarCuidadorPanel.repaint();
    }
    public EditarCuidador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        editarCuidadorPanel = new javax.swing.JPanel();
        labelTelefone = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JFormattedTextField();
        labelCidade = new javax.swing.JLabel();
        textFieldCidade = new javax.swing.JFormattedTextField();
        labelBairro = new javax.swing.JLabel();
        textFieldBairro = new javax.swing.JFormattedTextField();
        labelCep = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        textFieldCep = new javax.swing.JFormattedTextField();
        labelTitle = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        texfielName = new javax.swing.JFormattedTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldNumero = new javax.swing.JFormattedTextField();
        textFieldEmail = new javax.swing.JFormattedTextField();
        cadastrarButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1024, 1024));

        editarCuidadorPanel.setBackground(new java.awt.Color(255, 255, 255));
        editarCuidadorPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        editarCuidadorPanel.setPreferredSize(new java.awt.Dimension(1024, 1024));

        labelTelefone.setText("Numero De Telefone");



        textFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefoneActionPerformed(evt);
            }
        });

        labelCidade.setText("Cidade");

        labelBairro.setText("Bairro");

        labelCep.setText("CEP");

        labelNumero.setText("Numero");

        labelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Editar Novo Cuidador");

        labelName.setText("Nome");

        texfielName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfielNameActionPerformed(evt);
            }
        });

        labelEmail.setText("E-mail");

        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        cadastrarButton.setBackground(new java.awt.Color(0, 102, 204));
        cadastrarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarButton.setText("Editar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout editarCuidadorPanelLayout = new javax.swing.GroupLayout(editarCuidadorPanel);
        editarCuidadorPanel.setLayout(editarCuidadorPanelLayout);
        editarCuidadorPanelLayout.setHorizontalGroup(
                editarCuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editarCuidadorPanelLayout.createSequentialGroup()
                                .addContainerGap(236, Short.MAX_VALUE)
                                .addGroup(editarCuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarCuidadorPanelLayout.createSequentialGroup()
                                                .addGroup(editarCuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(editarCuidadorPanelLayout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addGroup(editarCuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(editarCuidadorPanelLayout.createSequentialGroup()
                                                                                .addComponent(labelCep)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(labelNumero))
                                                                        .addComponent(labelBairro)
                                                                        .addComponent(labelCidade)
                                                                        .addComponent(labelTelefone)
                                                                        .addComponent(labelName)
                                                                        .addComponent(labelEmail)
                                                                        .addComponent(textFieldEmail)
                                                                        .addComponent(texfielName)
                                                                        .addComponent(textFieldTelefone)
                                                                        .addComponent(textFieldCidade)
                                                                        .addComponent(textFieldBairro)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarCuidadorPanelLayout.createSequentialGroup()
                                                                                .addComponent(textFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                                                                .addComponent(textFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(editarCuidadorPanelLayout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                .addGap(219, 219, 219))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarCuidadorPanelLayout.createSequentialGroup()
                                                .addComponent(cadastrarButton)
                                                .addGap(319, 319, 319))))
        );
        editarCuidadorPanelLayout.setVerticalGroup(
                editarCuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editarCuidadorPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(texfielName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(editarCuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCep)
                                        .addComponent(labelNumero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editarCuidadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cadastrarButton)
                                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(editarCuidadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(editarCuidadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void texfielNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(texfielName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nome Invalido!");
        }else if(textFieldEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Email Invalido!");
        }else{
            Cuidador layoutcuidador = new Cuidador();
            JOptionPane.showMessageDialog(null,"Editado com Sucesso!");
            layoutcuidador.setNovoEmail(textFieldEmail.getText());
            layoutcuidador.setNovoNome(texfielName.getText());
            layoutcuidador.editTable();
            setconfpanel(layoutcuidador);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JPanel editarCuidadorPanel;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JFormattedTextField texfielName;
    private javax.swing.JFormattedTextField textFieldBairro;
    private javax.swing.JFormattedTextField textFieldCep;
    private javax.swing.JFormattedTextField textFieldCidade;
    private javax.swing.JFormattedTextField textFieldEmail;
    private javax.swing.JFormattedTextField textFieldNumero;
    private javax.swing.JFormattedTextField textFieldTelefone;
    // End of variables declaration
}
