package com.AnormaisEBruna.petshop.gui.views;


import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author detup
 */
public class imagemLogin extends javax.swing.JPanel {
    
    /**
     * Creates new form imagemLogin
     */
    BufferedImage imagemLogin;
    public imagemLogin() {
        initComponents();
        try {
            imagemLogin = ImageIO.read(new File("C:\\Users\\detup\\Desktop\\merda123\\src\\main\\java\\com\\AnormaisEBruna\\petshop\\assets\\imgs\\imageLogin.jpeg"));
        } catch (IOException ex) {
            Logger.getLogger(imagemLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(imagemLogin.getScaledInstance(555, 555, 0),0,0,null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
