package com.AnormaisEBruna.petshop.gui.views;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import com.AnormaisEBruna.petshop.contracts.gui.GUIManager;
import com.AnormaisEBruna.petshop.gui.components.pages.InitialPage;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author detup
 */
public class Usuarios extends JPanel{
    NovoUsuario cadastropage = new NovoUsuario();
    EditarUsuario editpage = new EditarUsuario();
    Object nome,email,novonome,novoemail;

    /**
     * Creates new form Usuarios
     */

    public void setconfpanel(JPanel p){
        p.setSize(1024,1024);
        p.setLocation(0,-20 ); // setlocation 0 p ser no meio da tela
        usuariosPanel.add(p);
        usuariosPanel.revalidate();
        usuariosPanel.repaint();
    }
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        usuariosPanel = new JPanel();
        jLabel4 = new JLabel();
        newUserButton = new JButton();
        editButton = new JButton();
        deletButton = new JButton();
        jScrollPane1 = new JScrollPane();
        tabelaUsuarios = new JTable();

        setPreferredSize(new Dimension(1024, 1024));
        setLayout(new FlowLayout());

        usuariosPanel.setBackground(new Color(255, 255, 255));
        usuariosPanel.setPreferredSize(new Dimension(1024, 1024));

        jLabel4.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Usuários");

        newUserButton.setText("Novo Usuário");
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });

        editButton.setText("Editar");
        editButton.setMaximumSize(new Dimension(75, 22));
        editButton.setMinimumSize(new Dimension(75, 22));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deletButton.setText("Excluir");
        deletButton.setMaximumSize(new Dimension(75, 22));
        deletButton.setMinimumSize(new Dimension(75, 22));
        deletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletButtonActionPerformed(evt);
            }
        });

        tabelaUsuarios.setModel(new DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Nome", "E-mail", "Último Login"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuarios.setToolTipText("");
        tabelaUsuarios.setShowGrid(false);
        jScrollPane1.setViewportView(tabelaUsuarios);

        GroupLayout usuariosPanelLayout = new GroupLayout(usuariosPanel);
        usuariosPanel.setLayout(usuariosPanelLayout);
        usuariosPanelLayout.setHorizontalGroup(
                usuariosPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(usuariosPanelLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(usuariosPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(usuariosPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                                        .addGroup(usuariosPanelLayout.createSequentialGroup()
                                                .addComponent(newUserButton)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(editButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deletButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addGap(125, 125, 125))
        );
        usuariosPanelLayout.setVerticalGroup(
                usuariosPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(usuariosPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(usuariosPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(deletButton, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newUserButton)
                                        .addComponent(editButton, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(371, Short.MAX_VALUE))
        );
        usuariosPanel.setBounds(0,0,-1,-1);
        add(usuariosPanel);
    }// </editor-fold>

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        usuariosPanel.removeAll();
        setconfpanel(cadastropage);

    }
    // atualiza os dados antes de voltar para essa pagina.
    public void refreshtable(){
        DefaultTableModel tabelaUsuario = (DefaultTableModel) tabelaUsuarios.getModel();
        Object[] dados = {nome,email,"indisponivel"};
        tabelaUsuario.addRow(dados);
    }
    public void setNome(Object nome){
        this.nome=nome;
    }
    public void setEmail(Object email){
        this.email=email;
    }
    public void editTable(){
        DefaultTableModel tabelaUsuario = (DefaultTableModel) tabelaUsuarios.getModel();
        tabelaUsuario.setValueAt(novonome, tabelaUsuarios.getSelectedRow(), 0);
        tabelaUsuario.setValueAt(novoemail, tabelaUsuarios.getSelectedRow(), 1);
        tabelaUsuario.setValueAt("agr",tabelaUsuarios.getSelectedRow(),2);

    }
    public void setNovoNome(Object novonome){
        this.novonome=novonome;
    }
    public void setNovoEmail(Object novoemail){
        this.novoemail=novoemail;
    }

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(tabelaUsuarios.getSelectedRow() != -1){
            usuariosPanel.removeAll();
            setconfpanel(editpage);
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um usúario para Editar");
        }
    }

    private void deletButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(tabelaUsuarios.getSelectedRow() != -1){
            DefaultTableModel tabelaUsuario = (DefaultTableModel) tabelaUsuarios.getModel();
            tabelaUsuario.removeRow(tabelaUsuarios.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um usúario para Excluir");
        }
    }

    // Variables declaration - do not modify
    public JPanel usuariosPanel;
    private JButton deletButton;
    private JButton editButton;
    private JLabel jLabel4;
    private JScrollPane jScrollPane1;
    private JButton newUserButton;
    private JTable tabelaUsuarios;

    // End of variables declaration
}

