package com.AnormaisEBruna.petshop.gui.views;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.IOException;

public class VerCuidador extends javax.swing.JPanel {



    public void setconfpanel(JPanel p){
        p.setSize(1024,1024);
        p.setLocation(0,-20 ); // setlocation 0 p ser no meio da tela
        cuidadorViewPanel.add(p);
        cuidadorViewPanel.revalidate();
        cuidadorViewPanel.repaint();
    }
    public VerCuidador() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        cuidadorViewPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDosPets = new javax.swing.JTable();
        labelNomeDoCuidador = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        visualizarPetButton = new javax.swing.JButton();

        cuidadorViewPanel.setPreferredSize(new Dimension(1024,1024));
        cuidadorViewPanel.setLayout(new FlowLayout());
        cuidadorViewPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaDosPets.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Id", "Nome Do Pet", "Raça"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDosPets);
        if (tabelaDosPets.getColumnModel().getColumnCount() > 0) {
            tabelaDosPets.getColumnModel().getColumn(0).setResizable(false);
            tabelaDosPets.getColumnModel().getColumn(1).setResizable(false);
            tabelaDosPets.getColumnModel().getColumn(2).setResizable(false);
        }

        labelNomeDoCuidador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNomeDoCuidador.setText("Nome Do Cuidador");

        sairButton.setText("Voltar");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    sairButtonActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        visualizarPetButton.setText("Visualizar Pet");
        visualizarPetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarPetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(visualizarPetButton))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(labelNomeDoCuidador)
                                                .addGap(45, 45, 45)))
                                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(labelNomeDoCuidador)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sairButton)
                                        .addComponent(visualizarPetButton))
                                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cuidadorViewPanelLayout = new javax.swing.GroupLayout(cuidadorViewPanel);
        cuidadorViewPanel.setLayout(cuidadorViewPanelLayout);
        cuidadorViewPanelLayout.setHorizontalGroup(
                cuidadorViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuidadorViewPanelLayout.createSequentialGroup()
                                .addContainerGap(523, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(503, 503, 503))
        );
        cuidadorViewPanelLayout.setVerticalGroup(
                cuidadorViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cuidadorViewPanelLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(cuidadorViewPanel);
    }// </editor-fold>

    private void visualizarPetButtonActionPerformed(ActionEvent evt) {
        // Resolver depois
//        VerPet visualizarPet = new VerPet();
//        cuidadorViewPanel.removeAll();
//        setconfpanel(visualizarPet);
    }

    private void sairButtonActionPerformed(ActionEvent evt) throws IOException {
        Cuidador layoutCuidador = new Cuidador();
        cuidadorViewPanel.removeAll();
        setconfpanel(layoutCuidador);

    }


    // Variables declaration - do not modify
    private javax.swing.JPanel cuidadorViewPanel;
    private javax.swing.JLabel labelNomeDoCuidador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sairButton;
    private javax.swing.JTable tabelaDosPets;
    private javax.swing.JButton visualizarPetButton;
    // End of variables declaration
}
